# working with data part 2
## V40 Permutation

In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame


In [5]:
dframe=DataFrame(np.arange(16).reshape(4,4))
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [10]:
 np.random.randn(5)

array([ 0.52168013, -0.41192018, -0.50975352,  0.21806989, -0.41087243])

In [12]:
blender = np.random.permutation(4)
#permutation = جایگشت

In [13]:
blender

array([3, 1, 0, 2])

In [14]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [21]:
dframe.take(blender)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11

In [20]:
dframe.take(blender,axis=1)

3   1   0   2
0   3   1   0   2
1   7   5   4   6
2  11   9   8  10
3  15  13  12  14

In [16]:
box=np.array([1,2,3])

In [17]:
#permutation with replacement ==> randint
shaker=np.random.randint(0,len(box),size=10)
shaker


array([2, 0, 0, 0, 1, 0, 2, 1, 0, 0])

In [18]:
hand_grabs=box.take(shaker)
hand_grabs

array([3, 1, 1, 1, 2, 1, 3, 2, 1, 1])

## V28 Merge

In [23]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series 

In [25]:
dframe1=DataFrame({'key':['X','Y','T','X','Y','Y'],
                  'data_set_1':np.arange(6)})
dframe1

key  data_set_1
0   X           0
1   Y           1
2   T           2
3   X           3
4   Y           4
5   Y           5

In [27]:
dframe2=DataFrame({'key':list('QYZ'),'data_set_2':list("123")})
dframe2

key data_set_2
0   Q          1
1   Y          2
2   Z          3

In [28]:
pd.merge(dframe1,dframe2)

key  data_set_1 data_set_2
0   Y           1          2
1   Y           4          2
2   Y           5          2

In [29]:
pd.merge(dframe1,dframe2,on='key')

key  data_set_1 data_set_2
0   Y           1          2
1   Y           4          2
2   Y           5          2

In [30]:
pd.merge(dframe1,dframe2,on='key',how='left')

key  data_set_1 data_set_2
0   X           0        NaN
1   Y           1          2
2   T           2        NaN
3   X           3        NaN
4   Y           4          2
5   Y           5          2

In [31]:
pd.merge(dframe1,dframe2,on='key',how='right')

key  data_set_1 data_set_2
0   Y         1.0          2
1   Y         4.0          2
2   Y         5.0          2
3   Q         NaN          1
4   Z         NaN          3

In [32]:
pd.merge(dframe1,dframe2,on='key',how='outer')

key  data_set_1 data_set_2
0   X         0.0        NaN
1   X         3.0        NaN
2   Y         1.0          2
3   Y         4.0          2
4   Y         5.0          2
5   T         2.0        NaN
6   Q         NaN          1
7   Z         NaN          3

In [33]:
dframe3=DataFrame({'key':list('XXXYZZ'),'data_set_3':range(6)})

In [34]:
dframe4=DataFrame({'key':list('YYXXZ'),'data_set_4':range(5)})

In [35]:
dframe3

key  data_set_3
0   X           0
1   X           1
2   X           2
3   Y           3
4   Z           4
5   Z           5

In [37]:
dframe4

key  data_set_4
0   Y           0
1   Y           1
2   X           2
3   X           3
4   Z           4

In [39]:
pd.merge(dframe3,dframe4)

key  data_set_3  data_set_4
0   X           0           2
1   X           0           3
2   X           1           2
3   X           1           3
4   X           2           2
5   X           2           3
6   Y           3           0
7   Y           3           1
8   Z           4           4
9   Z           5           4

In [41]:
df_left=DataFrame({'key1':['SF','SF','LA'],
                   'key2':['one','two','one'],
                  'left_data':[10,20,30]})
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [45]:
df_right=DataFrame({'key1':['SF','SF','LA','LA'],
                    'key2':['one','one','one','two'],
                   'right_data':[40,50,60,70]})
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [46]:
pd.merge(df_left,df_right,on=['key1','key2'],how='outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [47]:
pd.merge(df_left,df_right,on='key1')

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [48]:
pd.merge(df_left,df_right,on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

In [53]:
# For more info on merge parameters check out:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.merge.html'


In [54]:
import webbrowser

In [56]:
webbrowser.open(url)

True

# V29 Merge on index

In [72]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [73]:

df_left=DataFrame({'key':list('XYZXY'),'data_set':range(5)})

In [80]:
df_left

key  data_set
0   X         0
1   Y         1
2   Z         2
3   X         3
4   Y         4

In [83]:
df_right=DataFrame({'group_data':[10,20]},index=['X','Y'])
df_right

group_data
X          10
Y          20

In [87]:
pd.merge(df_left,df_right,left_on='key',right_index=True)

key  data_set  group_data
0   X         0          10
3   X         3          10
1   Y         1          20
4   Y         4          20

In [91]:
#hierarchy merging

In [94]:
df_left_hr=DataFrame({'key1':['SF','SF','SF','LA','LA'],
                     'key2':[10,20,30,20,30],
                      'data_set':np.arange(5.)})
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [96]:
df_right_hr=DataFrame(np.arange(10).reshape(5,2),
                     index=[['LA','LA','SF','SF','SF'],
                            [20,10,10,10,20]],
                     columns=['col_1','col_2'])
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [102]:
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

In [98]:
df_left.join(df_right)

key  data_set  group_data
0   X         0         NaN
1   Y         1         NaN
2   Z         2         NaN
3   X         3         NaN
4   Y         4         NaN

In [99]:
df_left


key  data_set
0   X         0
1   Y         1
2   Z         2
3   X         3
4   Y         4

In [100]:
df_right

group_data
X          10
Y          20

In [103]:
df_left.join(df_right)

key  data_set  group_data
0   X         0         NaN
1   Y         1         NaN
2   Z         2         NaN
3   X         3         NaN
4   Y         4         NaN

In [104]:
#??????

## V30 concatenate

In [107]:
import numpy as np
import pandas as pd
from pandas import Series , DataFrame

In [109]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [114]:
np.concatenate([arr1,arr1])
#np.concatenate([arr1,arr1],axis=0) ==> same as above

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
ser1=Series([0,1,2],index=list("TUV"))

In [119]:
ser2=Series([3,4],index=list('XY'))

In [120]:
ser1

T    0
U    1
V    2
dtype: int64

In [127]:
ser2

X    3
Y    4
dtype: int64

In [125]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [126]:
pd.concat([ser1,ser2],axis=1)

/Users/raka/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [128]:
#????

In [129]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [132]:
dframe1=DataFrame(np.random.randn(4,3),columns=list('XYZ'))
dframe1


X         Y         Z
0 -2.059137 -1.343464  0.028496
1 -2.426737  0.067407 -0.548723
2  0.743103 -0.302185  0.168056
3 -1.189887  0.428478 -0.312731

In [133]:
dframe2=DataFrame(np.random.randn(3,3),columns=list('YQX'))
dframe2



Y         Q         X
0 -0.755083 -0.871745  0.570049
1  2.075992 -0.970333  0.009565
2  0.212735  0.493652 -0.267189

In [134]:
pd.concat([dframe1,dframe2])

/Users/raka/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -2.059137 -1.343464  0.028496
1       NaN -2.426737  0.067407 -0.548723
2       NaN  0.743103 -0.302185  0.168056
3       NaN -1.189887  0.428478 -0.312731
0 -0.871745  0.570049 -0.755083       NaN
1 -0.970333  0.009565  2.075992       NaN
2  0.493652 -0.267189  0.212735       NaN

In [135]:
pd.concat([dframe1,dframe2],ignore_index=True)

/Users/raka/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -2.059137 -1.343464  0.028496
1       NaN -2.426737  0.067407 -0.548723
2       NaN  0.743103 -0.302185  0.168056
3       NaN -1.189887  0.428478 -0.312731
4 -0.871745  0.570049 -0.755083       NaN
5 -0.970333  0.009565  2.075992       NaN
6  0.493652 -0.267189  0.212735       NaN

In [136]:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'


## V31 Combine DataFrames

In [138]:
ser1=Series([2,np.nan,4,np.nan,6,np.nan],index=list('QRSTUV'))
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [140]:
ser2=Series(np.arange(len(ser1)),dtype=np.float64,index=list('QRSTUV'))
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [142]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [143]:
#if ser1 is null out ser2 else out ser1

In [145]:
#same as above and a kind of shortcut
ser1.combine_first(ser2) 

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [146]:
nan=np.nan
dframe_odds=DataFrame({'X':[1,nan,3,nan],
                      'Y':[nan,5,nan,7],
                      'Z':[nan,9,nan,11]})
dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [147]:
dframe_evens=DataFrame({'X':[2,4,nan,6,8],
                      'Y':[nan,10,12,14,16]})
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [148]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

##  V32 Reshaping 

In [154]:
dframe1=DataFrame(np.arange(8).reshape(2,4),
                  index=pd.Index(['LA','SF'],name='city'),
                 columns=pd.Index(['A','B','C','D'],name='letter'))
#the reason of useing pd.Index is for naming the index
dframe1


letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [155]:
dframe_st=dframe1.stack()

In [156]:
dframe_st

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int64

In [157]:
dframe_st.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [158]:
dframe_st.unstack('letter')

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [159]:
dframe_st.unstack('city')

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [161]:
ser1=Series([0,1,2],index=list('QXY'))
ser1

Q    0
X    1
Y    2
dtype: int64

In [162]:
ser2=Series([4,5,6],index=list('XYZ'))
ser2

X    4
Y    5
Z    6
dtype: int64

In [163]:
dframe=pd.concat([ser1,ser2],keys=['Alpha','Beta'])
dframe

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [164]:
dframe.unstack()

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [165]:
dframe.unstack().stack()

Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [166]:
dframe = dframe.unstack()

In [167]:
dframe

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [169]:
dframe.stack(dropna=False)

Alpha  Q    0.0
       X    1.0
       Y    2.0
       Z    NaN
Beta   Q    NaN
       X    4.0
       Y    5.0
       Z    6.0
dtype: float64

## V33 Pivoting  

In [170]:
# Lets create some data to play with:

# Note: It is not necessary to understand how this dataset was made to understand this Lecture.

#import pandas testing utility
import pandas.util.testing as tm; tm.N = 3

#Create a unpivoted function
def unpivot(frame):
    N, K = frame.shape
    
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    
    # Return the DataFrame
    return DataFrame(data, columns=['date', 'variable', 'value'])

#Set the DataFrame we'll be using
dframe = unpivot(tm.makeTimeDataFrame())

In [172]:
#Show the "stacked" data, note how there are multiple variables and values for the dates
dframe


date variable     value
0  2000-01-03        A  2.135851
1  2000-01-04        A -0.195695
2  2000-01-05        A  0.464390
3  2000-01-03        B -1.416309
4  2000-01-04        B -0.541128
5  2000-01-05        B -1.849426
6  2000-01-03        C  1.569107
7  2000-01-04        C  1.504576
8  2000-01-05        C -0.107914
9  2000-01-03        D  1.721147
10 2000-01-04        D -0.060582
11 2000-01-05        D -0.883624

In [175]:
dframe_piv=dframe.pivot('date','variable','value')
dframe_piv

variable           A         B         C         D
date                                              
2000-01-03  2.135851 -1.416309  1.569107  1.721147
2000-01-04 -0.195695 -0.541128  1.504576 -0.060582
2000-01-05  0.464390 -1.849426 -0.107914 -0.883624

## V34 Dyplicates in DataFrames

In [176]:
dframe=DataFrame({'key1':['A']*2+['B']*3,
                 'key2':[2,2,2,3,3]})
dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [177]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [178]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [179]:
dframe.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

In [182]:
dframe.drop_duplicates(['key1'],take_last=True)

TypeError: drop_duplicates() got an unexpected keyword argument 'take_last'

In [184]:
dframe.drop_duplicates(['key1'],keep='last')

key1  key2
1    A     2
4    B     3

keep : {‘first’, ‘last’, False}, default ‘first’

first : Drop duplicates except for the first occurrence.

last : Drop duplicates except for the last occurrence.

False : Drop all duplicates.

## V35 Mapping

In [193]:
#is used for creating or modifing a column 
dframe=DataFrame({'city':['Alma','Brian Head','Fox Park'],
                 'altitude':[3158,3000,2762]})
dframe

city  altitude
0        Alma      3158
1  Brian Head      3000
2    Fox Park      2762

In [190]:
state_map={'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}


In [191]:
dframe['state']=dframe['city'].map(state_map)


In [192]:
dframe

city  altitude     state
0        Alma      3158  Colorado
1  Brian Head      3000      Utah
2    Fox Park      2762   Wyoming

## V36 Replace 

In [194]:
ser1=Series(list('12341234'))
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: object

In [200]:
#because we used list in the above cell with should use string form here nut int64
ser1.replace('1',np.nan)

0    NaN
1      2
2      3
3      4
4    NaN
5      2
6      3
7      4
dtype: object

In [201]:
ser1=Series([1,2,3,4,1,2,3,4])
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [204]:
ser1.replace([1,3],[100,400])


0    100
1      2
2    400
3      4
4    100
5      2
6    400
7      4
dtype: int64

In [206]:
ser1.replace({4:np.nan})

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

## V37 Rename index

In [207]:
dframe=DataFrame(np.arange(12).reshape(3,4),
                index=['NY','LA','SF'],
                columns=list('ABCD'))
dframe

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [208]:
dframe.index.map(str.lower)

Index(['ny', 'la', 'sf'], dtype='object')

In [209]:
dframe.index = dframe.index.map(str.lower)
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [210]:
dframe.rename(index=str.title,columns=str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [213]:
dframe.rename(index={'ny':'New YORK'},columns={'A':'ALPHA'})


ALPHA  B   C   D
New YORK      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

In [214]:
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [215]:
dframe.rename(index={'ny':'NEW YORK'},inplace=True)

In [216]:
dframe

A  B   C   D
NEW YORK  0  1   2   3
la        4  5   6   7
sf        8  9  10  11

## V38 Bining

In [217]:
  years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]

In [218]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [220]:
decade_cat=pd.cut(years,decade_bins)
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [224]:
decade_cat.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]]
              closed='right',
              dtype='interval[int64]')

In [225]:
pd.value_counts(decade_cat)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [226]:
pd.cut(years,2)

[(1968.954, 1992.0], (1968.954, 1992.0], (1968.954, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], ..., (1968.954, 1992.0], (1968.954, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], (1992.0, 2015.0]]
Length: 11
Categories (2, interval[float64]): [(1968.954, 1992.0] < (1992.0, 2015.0]]

In [228]:
pd.cut(years,2,precision=1)

[(1969.0, 1992.0], (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], ..., (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], (1992.0, 2015.0]]
Length: 11
Categories (2, interval[float64]): [(1969.0, 1992.0] < (1992.0, 2015.0]]

## V39 Outliers

In [229]:
np.random.seed(12345)

In [230]:
dframe=DataFrame(np.random.randn(1000,4))
dframe.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [231]:
dframe.tail()

0         1         2         3
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

In [232]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [233]:
col=dframe[0]

In [234]:
col.head()

0   -0.204708
1    1.965781
2    0.769023
3    0.274992
4   -2.001637
Name: 0, dtype: float64

In [235]:
col[np.abs(col)>3]

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [236]:
#.abc absolute value

In [246]:
dframe[(np.abs(dframe)>3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

any(iterable)

Return True if any element of the iterable is true. If the iterable is empty, return False. 

Equivalent to:


def any(iterable):
    
    for element in iterable:
        
        if element:
            
            return True
    
    return False

In [247]:
dframe[np.abs(dframe)>3]=np.sign(dframe)*3

In [250]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000